apiVersion: v1
kind: ConfigMap
metadata:
  name: manage-users-config-map
  namespace: default
data:
  spring.datasource.url: "jdbc:postgresql://postgres-service:5432/manage-users"
  spring.datasource.driver: "org.postgresql.Driver"
  spring.datasource.username: "postgres"
  spring.datasource.password: "admin123"
  spring.datasource.tomcat.validation-query: "SELECT 1"
  spring.jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: "true"
